overwrite: true
schema: https://api-eu-central-1.graphcms.com/v2/ckvz13wjd3x7001wd2x9j6na1/master
documents: "graphql/**/*.graphql"
extensions:
  codegen:
    generates:
      generated/graphql.tsx:
        plugins:
          - "typescript"
          - "typescript-operations"
          - "typescript-react-apollo"
        config:
          reactApolloVersion: 3
          withHooks: true
          withHOC: false
          withComponent: false
          exportFragmentSpreadSubTypes: true
          documentMode: graphQLTag
      generated/page.tsx:
        config:
          documentMode: external
          importDocumentNodeExternallyFrom: ./graphql
          reactApolloVersion: 3
          withHooks: true
          withHOC: false
          apolloClientInstanceImport: "../lib/apolloClient"
        preset: import-types
        presetConfig:
          typesPath: ./graphql
        plugins:
          - graphql-codegen-apollo-next-ssr
    hooks:
      afterAllFileWrite:
        - prettier --write
