name: Test and Build

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          cache: "yarn"
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn lint
